### ISSUE TITLE
Need your help :)

### ISSUE THREAD

**Issue by PhamDong** [wadieskaf/Jigsaw-Sudoku#1]
Hi Guru :)
I'm newbie in Python but I like Sudoku
And I test your code with my own "Sudoku.txt" and "Sudoku_Regions.txt"
However it doesn't work.
Why? Please let me know Or at least fix it/or my own files.
Thanks and regars.
Pham Dong

Sudoku_Regions.txt
'region_1' : [(0,0),(0,1),(0,2),(1,0),(1,1),(1,2),(1.3),(2.2),(2,3)],
'region_2' : [(0,3),(0,4),(0,5),(0,6),(0,7),(1,4),(1,5),(1,6),(2,5)],
'region_3' : [(0,8),(1,7),(1,8),(2,6),(2,7),(2,8),(3,7),(3,8),(4,8)],
'region_4' : [(2,0),(2,1),(3,0),(3,1),(3,2),(4,1),(4,2),(4,3),(5,2)],
'region_5' : [(2,4),(3,3),(3,4),(3,5),(4,4),(5,3),(5,4),(5,5),(6,4)],
'region_6' : [(3,6),(4,5),(4,6),(4,7),(5,6),(5,7),(5,8),(6,7),(6,8)],
'region_7' : [(4,0),(5,0),(5,1),(6,0),(6,1),(6,2),(7,0),(7,1),(8,0)],
'region_8' : [(6,3),(7,2),(7,3),(7,4),(8,1),(8,2),(8,3),(8,4),(8,5)],
'region_9' : [(6,5),(6,6),(7,5),(7,6),(7,7),(7,8),(8,6),(8,7),(8,8)]   
Sudoku.txt
0,0,0,0,8,0,0,1,0
0,0,0,0,0,5,4,6,0
0,0,2,0,0,0,0,5,3
2,0,0,0,0,0,0,0,0
0,1,0,7,0,4,0,3,0
0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,5,0,1
0,0,8,3,0,0,0,0,0
0,0,0,0,0,0,0,0,0

**Comment by skafai** [comment]
You are using dots instead of commas in some places like : 'region_1' : [(0,0),(0,1),(0,2),(1,0),(1,1),(1,2),**(1.3),(2.2)**,(2,3)],

**Comment by PhamDong** [comment]
Woah
**Thanks U so much** And feedback soon :)
Pham Dong
